services:
  - type: web
    name: aorbo-django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn aorbo_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aorbo-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    autoDeploy: true
